name: CI-coverage
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - run: |
          php -v
          php -m.
          mkdir -p ./tests/Functional/config
          php ./test/Functional/console doctrine:database:create --env=test
          php ./test/Functional/console d:s:u -f --env=test
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          php_extensions: xdebug
          bootstrap: ./tests/bootstrap.php
          configuration: ./phpunit.xml.dist
          args: --coverage-text
        env:
          XDEBUG_MODE: coverage
          TEST_NAME: integration_test