name: CI-coverage
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v26
      - name: List all changed files
        run: |
          touch ${{ github.workspace }}/diff_files
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file" >> ${{ github.workspace }}/diff_files
          done
          pwd
          cat ${{ github.workspace }}/diff_files
      - uses: php-actions/composer@v5
      - run: |
          php -v
          php -m.
          mkdir -p ./tests/Functional/extra
          php ./tests/Functional/console doctrine:database:create --env=test
          php ./tests/Functional/console d:s:u -f --env=test
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v2
        with:
          php_extensions: xdebug
          bootstrap: ./tests/bootstrap.php
        env:
          XDEBUG_MODE: coverage
          TEST_NAME: integration_test
      - name: generate coverage config
        id: coverage-config
        run: |
          php phpunit.config.php
      - name: code coverage
        id: code-coverage
        run: |
          if [[ -s ${{ github.workspace }}/diff_files ]]; then
            XDEBUG_MODE=coverage php ./vendor/bin/phpunit --filter $(cat ${{ github.workspace }}/diff_files | grep 'src/' | sed 's/.*\///' | sed 's/\.php//' | paste -sd '|' - ) --coverage-text ;
          fi;